language: python
python:
  - "2.6"

before_install:
    - sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install node php5-cli

script: python quine.py > quine.js && node quine.js > quine.php && php quine.php > quine2.py && diff -s quine.py quine2.py
