language: python
python:
  - "2.6"

sudo: false

addons:
  apt:
    packages:
    - node
    - php5-cli

script: python quine.py > quine.js && node quine.js > quine.php && php quine.php > quine2.py && diff -s quine.py quine2.py
